### ISSUE TITLE
Update `tfn` schema

### ISSUE THREAD

**Issue by jingyujzhang** [iangow-public/wrds_pg#30]
@iangow: I would like to update `tfn` schema and got some errors when downloading `tfn.company`. Both `python` and `perl` reported same error (from psql). Other tables that `python` code reported an error could be imported with `perl` code.

```
Updated tfn.company is available. Getting from WRDS.
Getting schema for tfn.company
NOTICE:  table "company" does not exist, skipping
Beginning file import at 22:56:26
Importing data into tfn.company.
ERROR:  unquoted carriage return found in data
HINT:  Use quoted CSV field to represent carriage return.
CONTEXT:  COPY company, line 25842
Result of system command: 256
Completed file import at 22:56:29
Last modified: 04/03/2018 06:03:51
```

**Comment by iangow** [comment]
You may need to use the `fix_cr = True` argument.

https://github.com/iangow-public/wrds_pg/blob/7a37492f98f98db832cdaebd2277edfc8faf744f/wrds_fetch.py#L326

**Comment by iangow** [comment]
It may make sense to add a little documentation for the main function in `wrds_fetch.py` so that you don’t need to search the source code to understand what’s going on. Some of this could be done as “doc strings” in the source code itself.

**Comment by iangow** [comment]
Note that some of the `tfn` data has serious issues (documented somewhere on WRDS). Depending on what you are using it for, there may be better alternatives.

**Comment by jingyujzhang** [comment]
It seems that crsp stopped updating `tfn.idfhist` and `tfn.idfnames`.
