### ISSUE TITLE
Add crsp.tfz_ft to update_crsp.py

### ISSUE THREAD

**Issue by iangow** [iangow-public/wrds_pg#35]
Table is listed [here](https://wrds-web.wharton.upenn.edu/wrds/ds/crsp/a_treas/tfz_ft/index.cfm?navId=134). Issue is discussed [here](https://github.com/azakolyukina/nonans_product/issues/99#issuecomment-410003303) and feeds into  [this](https://github.com/azakolyukina/nonans_product/issues/96) issue.

**Comment by azakolyukina** [comment]
@jingyujzhang and @iangow: 

Could you please update all the scripts such that they also sets `xxx_access` privileges automatically; otherwise, we will keep on having to add `xxx_access` down the road anyways.

```SQL
GRANT SELECT ON crsp.tfz_ft TO crsp_access
```

**Comment by iangow** [comment]
That is (I believe) already embedded in the `update_comp.py` script that @jingyuzhang needs to modify.

**Comment by jingyujzhang** [comment]
Quoted from wrds customer support's email.
```
The error is correct, the table "tfz_ft," does not exist. Behind the scenes this web 
query form is joining two tables on the fly. The tables this query is joining are 
"crsp.tfz_idx" and either "crsp.tfz_dly_ft" or "crsp.tfz_mth_ft" (depending on if 
you want daily or monthly data) by the variable "kytreasnox."

Here are some links to the information about these tables: 
https://wrds-web.wharton.upenn.edu/wrds/tools/variable.cfm?library_id=137&file_id=77140
https://wrds-web.wharton.upenn.edu/wrds/tools/variable.cfm?library_id=137&file_id=77137
https://wrds-web.wharton.upenn.edu/wrds/tools/variable.cfm?library_id=137&file_id=77147
```
`crsp.tfz_ft` is not a real table in wrds database, so both python and perl code broke. I modified python code only to calculate this table. Since one of the base tables has datatype error, which is rare, I modified `wrds_fetch.py` in a dirty way. The permission issue related to derivative tables has been fixed.

`Crsp` is now up to date.

**Comment by jingyujzhang** [comment]
> That is (I believe) already embedded in the update_comp.py script that @jingyujzhang needs to modify.

@iangow: `Comp` schema doesn't have permission issues. The tables are fine right now.

**Comment by iangow** [comment]
You should *not* `wrds_fetch.py` "in a dirty way." 

That code has to work for all tables on WRDS and should not be mangled to handle an issue specific to one table.

If some specific code is needed for `tfz_ft`, then I think it's better to put that in `tfz_ft`. Better, it may make sense to work out which table is wanted (`crsp.tfz_dly_ft` or `crsp.tfz_mth_ft`) and then write code to merge these with `crsp.tfz_idx` to make `crsp.tfz_ft`. This code can go in `update_crsp.py`. See code there for guidance.

**Comment by jingyujzhang** [comment]
I didn't put merging table part to `wrds_fetch.py`. The datatype error needs to be fixed in `wrds_fetch` otherwise the table can't be uploaded to PG. The current funtions in `wrds_fetch` don't provide an interface to make this change.

**Comment by iangow** [comment]
Note that you use the underlying functions to get more detail if that helps:

```
from wrds_fetch import get_table_sql
get_table_sql("tfz_dly_ft", "crsp", "iangow", return_sql=False)
```

[Untitled1-2.pdf](https://github.com/iangow-public/wrds_pg/files/2269278/Untitled1-2.pdf)

**Comment by iangow** [comment]
Maybe put the content of the email from comment below in the code for posterity.  

https://github.com/iangow-public/wrds_pg/issues/35#issuecomment-411226414

**Comment by jingyujzhang** [comment]
Done.
