### ISSUE TITLE
Move functions to `misc`

### ISSUE THREAD

**Issue by iangow** [iangow-public/wrds_pg#37]
I think there is code somewhere to create PG functions. Try `azakolyukina/misc` repository. This is a very useful function that may or may not be there (the name `eomonth` is based on an Excel function that does the same thing).

https://github.com/iangow-public/wrds_pg/blob/d80009c3459bb6bf51ee9bc61dd4ea9714705604/crsp/crsp_make_mrets.sql#L4

**Comment by jingyujzhang** [comment]
This function is [there](https://github.com/azakolyukina/misc/blob/master/pg_func/create_func_eomonth.R).
