### ISSUE TITLE
lookup the schema and file

### ISSUE THREAD

**Issue by Spider08** [iangow-public/wrds_pg#42]
Trying to see where we can look up a schema and file name for using this library for files that is not yet been supported with this library.

I can login using ssh and see the file there but somehow not able to run it using the command.
I am thinking the schema name I am using may be wrong. Is there any way to look up the filename and schema for a specific file or library ?

For example - looking for the firm_ratio file from the wrdsapps
so if you login you can see the file 

wrdsapps -> sasdata -> finratio -> firm_ratio.sas7bdat

- but this command does not run. 
updated = wrds_update("firm_ratio", "wrdsapps", engine, wrds_id)

Any pointers or help appreciated and thanks for the wonderful library

**Comment by iangow** [comment]
Try:

```python
updated = wrds_update("firm_ratio", "finratio", engine, wrds_id)
```

This assumes that in SAS you'd say:

```sas
data my_data;
    set finratio.firmratio;
run;
```

**Comment by iangow** [comment]
I look up libraries using the WRDS.

In [this case](https://wrds-web.wharton.upenn.edu/wrds/ds/wrdsapps/finratiofirm/index.cfm?navId=401), you may want:

```python
updated = wrds_update("finratiofirm", "wrdsapps", engine, wrds_id)
```

**Comment by Spider08** [comment]
Thanks for the replies. Same here I can run a web query without any issues. 

But just testing the access and whether the script can see the file, it fails.
test_string = get_modified_str("firm_ratio", "wrdsapps", wrds_id)
print test_string

Not really proficient in SAS, so not sure how it works. Is there any way to look up the schema of the files and corresponding mapping through SAS.? I can see the file names and directory structure through ssh and even through web query, but not sure how SAS see those files when we run it through the script and how to map it if there is no corresponding mapping. So in other words if we can scp the file there should be a way to run it through the script right.?

Thanks again

**Comment by iangow** [comment]
> So in other words if we can scp the file there should be a way to run it through the script right.?

Yes, you can specify the named argument `fpath` instead of `wrds_id` to point the script to a local file. Unfortunately, this requires a local instance of SAS (and I don't have one). That said, if you are able to `git clone` the repository onto a machine that has SAS, then you can probably get it to work.

**Comment by Spider08** [comment]
Same here. No access to instance of SAS other than the wrds cloud. 

So our script can only see the file if there is an existing mapping else it fails ? And where can we look all the existing SAS mappings ?

**Comment by Spider08** [comment]
And is there way to add our own schema before we call the scripts?

**Comment by iangow** [comment]
If you specify `fpath`, there is no need to set up a SAS "schema" (the script creates a temporary library). I don't recall, but I *believe* that if you specify a `schema` that does not exist in the database, the script will create it.

**Comment by iangow** [comment]
It seems that your WRDS home directory is given the `libname` "`home`". So you can get a SAS data file in your home directory in PostgreSQL by doing this:

```python
from wrds2pg.wrds2pg import wrds_update

updated = wrds_update("fog_data", "home")
```

where the SAS file in my home directory is `fog_data.sas7bdat`. This assumes that there is a schema in the PostgreSQL database named `home` (this is where the data will go). But simply run `CREATE SCHEMA home;` in PostgreSQL to create this before running the R code (creating the schema in the Python code is something I will add at some point).
