### ISSUE TITLE
Trim instructions; refer to wrds2pg

### ISSUE THREAD

**Issue by iangow** [iangow-public/wrds_pg#43]
Basically this repository should become one that uses the package installed from https://github.com/iangow/wrds2pg. It may be that this repository just illustrates how to use that other code (it may make sense to have `aaz` and `master` branches to reflect differences in what @azakolyukina and I have in our respective databases.

Documentation here should refer user to https://github.com/iangow/wrds2pg. Perhaps some of the documentation here belongs there.

**Comment by jingyujzhang** [comment]
Updated `README` in both repositories.
